import { type Product } from './index.ts';

export const products: Product[] = [
  // === PRINTERS ===
  {
    id: 'p001',
    name: 'Canon PIXMA G3470 Кольоровий струменевий',
    category: 'printers',
    brand: 'Canon',
    price: 6499,
    image: 'https://images.unsplash.com/photo-1612815292517-8e732db6ec94?w=600&q=80',
    description: 'Кольоровий струменевий принтер із системою безперервної подачі чорнила MEGATANK. Ідеально підходить для домашнього офісу та малого бізнесу. Забезпечує низьку вартість друку та чудову якість зображень.',
    tags: [
      { label: 'Бренд', value: 'Canon' },
      { label: 'Тип', value: 'Струменевий' },
      { label: 'Формат', value: 'A4' },
    ],
    inStock: true,
    colorPrint: true,
    wireless: true,
    inkjet: true,
    duplex: false,
    a3: false,
    maxDpi: 4800,
  },
  {
    id: 'p002',
    name: 'HP LaserJet Pro M404dn Монохромний',
    category: 'printers',
    brand: 'HP',
    price: 9200,
    image: 'https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&q=80',
    description: 'Надійний монохромний лазерний принтер для середніх офісів. Двостороннє автоматичне друкування, висока швидкість 40 стор/хв, дротова мережа.',
    tags: [
      { label: 'Бренд', value: 'HP' },
      { label: 'Тип', value: 'Лазерний' },
      { label: 'Формат', value: 'A4' },
    ],
    inStock: true,
    colorPrint: false,
    wireless: false,
    laser: true,
    duplex: true,
    a3: false,
    maxDpi: 1200,
  },
  {
    id: 'p003',
    name: 'Epson EcoTank L8180 Кольоровий A3+',
    category: 'printers',
    brand: 'Epson',
    price: 18500,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    description: 'Фотоприн тер A3+ з 6 кольорами та системою EcoTank. Ідеальний для якісного фотодруку великого формату. Безпровідне підключення, дисплей, CD/DVD-друк.',
    tags: [
      { label: 'Бренд', value: 'Epson' },
      { label: 'Тип', value: 'Струменевий' },
      { label: 'Формат', value: 'A3+' },
    ],
    inStock: true,
    colorPrint: true,
    wireless: true,
    inkjet: true,
    duplex: true,
    a3: true,
    maxDpi: 5760,
  },
  {
    id: 'p004',
    name: 'Brother HL-L8360CDW Кольоровий лазерний',
    category: 'printers',
    brand: 'Brother',
    price: 14800,
    image: 'https://images.unsplash.com/photo-1612815292517-8e732db6ec94?w=600&q=80',
    description: 'Швидкий кольоровий лазерний принтер для бізнесу. 31 стор/хв кольорового друку, автоматичний дуплекс, Wi-Fi, NFC.',
    tags: [
      { label: 'Бренд', value: 'Brother' },
      { label: 'Тип', value: 'Лазерний' },
      { label: 'Формат', value: 'A4' },
    ],
    inStock: false,
    colorPrint: true,
    wireless: true,
    laser: true,
    duplex: true,
    a3: false,
    maxDpi: 2400,
  },

  // === SCANNERS ===
  {
    id: 's001',
    name: 'Epson Perfection V39 Планшетний',
    category: 'scanners',
    brand: 'Epson',
    price: 3200,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
    description: 'Компактний планшетний сканер A4 з роздільною здатністю 4800 dpi. Підходить для сканування документів, фото та слайдів. Підключення USB.',
    tags: [
      { label: 'Бренд', value: 'Epson' },
      { label: 'Тип', value: 'Планшетний' },
    ],
    inStock: true,
    portableScanner: false,
    autoFeed: false,
    maxDpi: 4800,
  },
  {
    id: 's002',
    name: 'Canon DR-C230 Документний з автоподачею',
    category: 'scanners',
    brand: 'Canon',
    price: 12900,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
    description: 'Офісний документний сканер з автоподачею до 60 аркушів. Двостороннє сканування, 30 стор/хв, підключення USB 3.1.',
    tags: [
      { label: 'Бренд', value: 'Canon' },
      { label: 'Тип', value: 'Документний' },
    ],
    inStock: true,
    portableScanner: false,
    autoFeed: true,
    maxDpi: 600,
  },
  {
    id: 's003',
    name: 'Brother ADS-1200 Портативний',
    category: 'scanners',
    brand: 'Brother',
    price: 5800,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
    description: 'Компактний портативний сканер з автоподачею. Живлення від USB, ідеальний для роботи в дорозі. 25 стор/хв, двостороннє сканування.',
    tags: [
      { label: 'Бренд', value: 'Brother' },
      { label: 'Тип', value: 'Портативний' },
    ],
    inStock: true,
    portableScanner: true,
    autoFeed: true,
    maxDpi: 600,
  },

  // === MFP (Багатофункціональні пристрої) ===
  {
    id: 'm001',
    name: 'HP Color LaserJet Pro MFP M479fdw',
    category: 'mfp',
    brand: 'HP',
    price: 21500,
    image: 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&q=80',
    description: 'Кольоровий лазерний БФП з факсом, Wi-Fi, дуплексом та сенсорним дисплеєм. Друк, копіювання, сканування, факс в одному пристрої.',
    tags: [
      { label: 'Бренд', value: 'HP' },
      { label: 'Тип', value: 'Лазерний БФП' },
    ],
    inStock: true,
    colorPrint: true,
    wireless: true,
    laser: true,
    duplex: true,
    a3: false,
    touchScreen: true,
    autoFeed: true,
  },
  {
    id: 'm002',
    name: 'Epson EcoTank ET-5850 Струменевий БФП',
    category: 'mfp',
    brand: 'Epson',
    price: 16200,
    image: 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&q=80',
    description: 'Струменевий БФП з безперервною подачею чорнила, Wi-Fi, автоподавачем документів. Надзвичайно низька вартість сторінки.',
    tags: [
      { label: 'Бренд', value: 'Epson' },
      { label: 'Тип', value: 'Струменевий БФП' },
    ],
    inStock: true,
    colorPrint: true,
    wireless: true,
    inkjet: true,
    duplex: true,
    a3: false,
    touchScreen: true,
    autoFeed: true,
  },
  {
    id: 'm003',
    name: 'Canon i-SENSYS MF445dw Монохромний БФП',
    category: 'mfp',
    brand: 'Canon',
    price: 11800,
    image: 'https://images.unsplash.com/photo-1563203369-26f2e4a5ccf7?w=600&q=80',
    description: 'Монохромний лазерний БФП для малого бізнесу. 38 стор/хв, Wi-Fi, дуплекс, автоподавач 50 аркушів.',
    tags: [
      { label: 'Бренд', value: 'Canon' },
      { label: 'Тип', value: 'Монохромний БФП' },
    ],
    inStock: true,
    colorPrint: false,
    wireless: true,
    laser: true,
    duplex: true,
    autoFeed: true,
    touchScreen: false,
  },

  // === INK (Чорнила) ===
  {
    id: 'i001',
    name: 'Epson 103 EcoTank Чорнило Чорне 65мл',
    category: 'ink',
    brand: 'Epson',
    price: 320,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80',
    description: 'Оригінальне чорне чорнило для принтерів серії EcoTank. Об\'єм 65 мл, висока стійкість до вигоряння, насичений чорний колір.',
    tags: [
      { label: 'Бренд', value: 'Epson' },
      { label: 'Колір', value: 'Чорний' },
    ],
    inStock: true,
    oem: true,
    refill: false,
  },
  {
    id: 'i002',
    name: 'Canon GI-490 Заправне чорнило Cyan 70мл',
    category: 'ink',
    brand: 'Canon',
    price: 380,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80',
    description: 'Оригінальне чорнило Cyan для серії PIXMA G. 70 мл, понад 7000 сторінок при 5% заповненні.',
    tags: [
      { label: 'Бренд', value: 'Canon' },
      { label: 'Колір', value: 'Cyan' },
    ],
    inStock: true,
    oem: true,
    refill: false,
  },
  {
    id: 'i003',
    name: 'ColorWay Сумісне чорнило для HP 100мл Magenta',
    category: 'ink',
    brand: 'ColorWay',
    price: 180,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80',
    description: 'Сумісне чорнило для принтерів HP. 100 мл, збалансований колір, стійкий до вигоряння. Відмінне співвідношення ціна/якість.',
    tags: [
      { label: 'Бренд', value: 'ColorWay' },
      { label: 'Колір', value: 'Magenta' },
    ],
    inStock: true,
    oem: false,
    refill: true,
  },
  {
    id: 'i004',
    name: 'Brother LC3213 Набір чорнил 4 кольори',
    category: 'ink',
    brand: 'Brother',
    price: 890,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80',
    description: 'Оригінальний набір із 4 картриджів: чорний, блакитний, пурпурний, жовтий. Для принтерів Brother MFC і DCP.',
    tags: [
      { label: 'Бренд', value: 'Brother' },
      { label: 'Тип', value: 'Набір' },
    ],
    inStock: true,
    oem: true,
    refill: false,
  },

  // === TONER (Картриджі) ===
  {
    id: 't001',
    name: 'HP 30A CF230A Лазерний картридж Чорний',
    category: 'toner',
    brand: 'HP',
    price: 1850,
    image: 'https://images.unsplash.com/photo-1601524909162-ae8725290836?w=600&q=80',
    description: 'Оригінальний лазерний картридж HP 30A для LaserJet Pro M203/MFP M227. Ресурс 1600 сторінок при 5% заповненні.',
    tags: [
      { label: 'Бренд', value: 'HP' },
      { label: 'Тип', value: 'Тонер-картридж' },
    ],
    inStock: true,
    oem: true,
    refill: false,
  },
  {
    id: 't002',
    name: 'Canon 057H Лазерний картридж (велика ємність)',
    category: 'toner',
    brand: 'Canon',
    price: 2600,
    image: 'https://images.unsplash.com/photo-1601524909162-ae8725290836?w=600&q=80',
    description: 'Оригінальний картридж підвищеної ємності для i-SENSYS MF443dw/MF445dw. Ресурс 10 000 сторінок.',
    tags: [
      { label: 'Бренд', value: 'Canon' },
      { label: 'Тип', value: 'Тонер-картридж XL' },
    ],
    inStock: true,
    oem: true,
    refill: false,
  },
  {
    id: 't003',
    name: 'Compatibles Epson S110079 Сумісний картридж Cyan',
    category: 'toner',
    brand: 'Compatibles',
    price: 680,
    image: 'https://images.unsplash.com/photo-1601524909162-ae8725290836?w=600&q=80',
    description: 'Сумісний кольоровий картридж для Epson AL-C300/C400. Ресурс 3000 сторінок. Гарантована якість друку.',
    tags: [
      { label: 'Бренд', value: 'Compatibles' },
      { label: 'Колір', value: 'Cyan' },
    ],
    inStock: true,
    oem: false,
    refill: true,
  },

  // === PAPER (Папір) ===
  {
    id: 'pa001',
    name: 'Navigator Universal A4 80г/м² 500 аркушів',
    category: 'paper',
    brand: 'Navigator',
    price: 165,
    image: 'https://images.unsplash.com/photo-1574950578143-858c6fc58922?w=600&q=80',
    description: 'Офісний папір преміум класу A4, 80 г/м², пачка 500 аркушів. Підходить для всіх типів принтерів і копіювальних апаратів.',
    tags: [
      { label: 'Бренд', value: 'Navigator' },
      { label: 'Формат', value: 'A4' },
    ],
    inStock: true,
    a3: false,
  },
  {
    id: 'pa002',
    name: 'Lomond Photo Paper Глянцевий A4 230г/м² 50л',
    category: 'paper',
    brand: 'Lomond',
    price: 420,
    image: 'https://images.unsplash.com/photo-1574950578143-858c6fc58922?w=600&q=80',
    description: 'Глянцевий фотопапір для струменевого друку. 50 аркушів A4, 230 г/м², яскраві кольори, швидке висихання.',
    tags: [
      { label: 'Бренд', value: 'Lomond' },
      { label: 'Тип', value: 'Фотопапір' },
    ],
    inStock: true,
    a3: false,
  },
  {
    id: 'pa003',
    name: 'Xerox Premier A3 80г/м² 500 аркушів',
    category: 'paper',
    brand: 'Xerox',
    price: 320,
    image: 'https://images.unsplash.com/photo-1574950578143-858c6fc58922?w=600&q=80',
    description: 'Офісний папір формату A3, 80 г/м², пачка 500 аркушів. Кліматично нейтральне виробництво.',
    tags: [
      { label: 'Бренд', value: 'Xerox' },
      { label: 'Формат', value: 'A3' },
    ],
    inStock: true,
    a3: true,
  },

  // === SHREDDERS (Шредери) ===
  {
    id: 'sh001',
    name: 'Fellowes Powershred 79Ci Шредер для дому',
    category: 'shredders',
    brand: 'Fellowes',
    price: 4200,
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&q=80',
    description: 'Домашній шредер з перехресним різанням. Знищує до 9 аркушів за раз, картки та скріпки. Бункер 20 л.',
    tags: [
      { label: 'Бренд', value: 'Fellowes' },
      { label: 'Рівень', value: 'P-4' },
    ],
    inStock: true,
    crossCut: true,
    sheetCapacity: 9,
  },
  {
    id: 'sh002',
    name: 'Rexel Momentum X410 Офісний шредер',
    category: 'shredders',
    brand: 'Rexel',
    price: 7800,
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&q=80',
    description: 'Тихий офісний шредер з авто-живленням. До 10 аркушів, рівень безпеки P-4, автоматичне подавання папера, безперервна робота.',
    tags: [
      { label: 'Бренд', value: 'Rexel' },
      { label: 'Рівень', value: 'P-4' },
    ],
    inStock: true,
    crossCut: true,
    sheetCapacity: 10,
    autoFeed: true,
  },

  // === LAMINATORS (Ламінатори) ===
  {
    id: 'l001',
    name: 'GBC Foton 30 Ламінатор A4 автоматичний',
    category: 'laminators',
    brand: 'GBC',
    price: 5600,
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80',
    description: 'Автоматичний ламінатор A4 для офісу. Швидкість 30 см/хв, підтримує плівки 80-125 мкм, готовий до роботи за 60 сек.',
    tags: [
      { label: 'Бренд', value: 'GBC' },
      { label: 'Формат', value: 'A4' },
    ],
    inStock: true,
    coldLamination: false,
    a3: false,
  },
  {
    id: 'l002',
    name: 'Leitz iLAM Home Office A3 Ламінатор',
    category: 'laminators',
    brand: 'Leitz',
    price: 3100,
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80',
    description: 'Ламінатор A3 для дому та офісу. Підтримує гарячу та холодну ламінацію, плівки 80-250 мкм, формат до A3.',
    tags: [
      { label: 'Бренд', value: 'Leitz' },
      { label: 'Формат', value: 'A3' },
    ],
    inStock: true,
    coldLamination: true,
    a3: true,
  },

  // === PROJECTORS (Проектори) ===
  {
    id: 'pr001',
    name: 'Epson EB-W52 WXGA Проектор 4000 лм',
    category: 'projectors',
    brand: 'Epson',
    price: 22800,
    image: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&q=80',
    description: 'Бізнес-проектор WXGA (1280x800), 4000 лм, Wi-Fi, HDMI, USB. Ідеальний для конференц-залів і аудиторій.',
    tags: [
      { label: 'Бренд', value: 'Epson' },
      { label: 'Роздільність', value: 'WXGA' },
    ],
    inStock: true,
    wireless: true,
    hd: false,
  },
  {
    id: 'pr002',
    name: 'Optoma UHD38x 4K Ігровий Проектор',
    category: 'projectors',
    brand: 'Optoma',
    price: 41500,
    image: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&q=80',
    description: '4K UHD проектор для ігор та домашнього кінотеатру. 3800 лм, 4K, 240 Гц, HDMI 2.0, HDR10, час відгуку 4.2 мс.',
    tags: [
      { label: 'Бренд', value: 'Optoma' },
      { label: 'Роздільність', value: '4K UHD' },
    ],
    inStock: true,
    wireless: false,
    hd: true,
  },

  // === PLOTTERS (Плотери) ===
  {
    id: 'pl001',
    name: 'HP DesignJet T650 36" Плотер A0',
    category: 'plotters',
    brand: 'HP',
    price: 58000,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    description: 'Широкоформатний струменевий плотер 36 дюймів для CAD та GIS. Wi-Fi, USB, Ethernet. Рулонний та аркушевий папір.',
    tags: [
      { label: 'Бренд', value: 'HP' },
      { label: 'Формат', value: 'A0 (36")' },
    ],
    inStock: true,
    colorPrint: true,
    wireless: true,
    wideFormat: true,
    inkjet: true,
  },
  {
    id: 'pl002',
    name: 'Epson SureColor SC-T3100 Широкоформатний',
    category: 'plotters',
    brand: 'Epson',
    price: 47000,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    description: 'Плотер A1 з роздільністю 2400 dpi. Печатка на рулонному папері, підставка в комплекті, Wi-Fi, USB 3.0.',
    tags: [
      { label: 'Бренд', value: 'Epson' },
      { label: 'Формат', value: 'A1 (24")' },
    ],
    inStock: false,
    colorPrint: true,
    wireless: true,
    wideFormat: true,
    inkjet: true,
  },
];

export const BRANDS = [...new Set(products.map((p) => p.brand))].sort();

export const MAX_PRICE = Math.max(...products.map((p) => p.price));
export const MIN_PRICE = Math.min(...products.map((p) => p.price));
