import { type Product } from './index.ts';

export const products: Product[] = [
  // === PRINTERS ===
  {
    id: 'p001',
    name: 'Canon PIXMA G3470 Кольоровий струменевий',
    category: 'printers',
    brand: 'Canon',
    price: 6499,
    image: 'https://files.foxtrot.com.ua/PhotoNew/hb3dem9f1t1_638194334761717420.webp',
    description: 'Кольоровий струменевий принтер із системою безперервної подачі чорнила MEGATANK. Ідеально підходить для домашнього офісу та малого бізнесу. Забезпечує низьку вартість друку та чудову якість зображень.',
    inStock: false,
    colorPrint: true,
    wireless: true,
    inkjet: true,
    a4: true,
    maxDpi: 4800,
  },
  {
    id: 'p002',
    name: 'HP LaserJet Pro M404dn Монохромний',
    category: 'printers',
    brand: 'HP',
    price: 9200,
    image: 'https://cdn.comfy.ua/media/catalog/product/cache/5/image/600x/9df78eab33525d08d6e5fb8d27136e95/h/p/hp_laserjet_pro_3003dn_3g653a_3_.jpg',
    description: 'Надійний монохромний лазерний принтер для середніх офісів. Двостороннє автоматичне друкування, висока швидкість 40 стор/хв, дротова мережа.',
    inStock: true,
    laser: true,
    duplex: true,
    a4: true,
    maxDpi: 1200,
  },
  {
    id: 'p003',
    name: 'Epson EcoTank L8180 Кольоровий A3+',
    category: 'printers',
    brand: 'Epson',
    price: 18500,
    image: 'https://content2.rozetka.com.ua/goods/images/big/407429814.jpg',
    description: 'Фотоприн тер A3+ з 6 кольорами та системою EcoTank. Ідеальний для якісного фотодруку великого формату. Безпровідне підключення, дисплей, CD/DVD-друк.',
    inStock: true,
    colorPrint: true,
    wireless: true,
    inkjet: true,
    duplex: true,
    a3: true,
    maxDpi: 5760,
  },
  {
    id: 'p004',
    name: 'Brother HL-L8360CDW Кольоровий лазерний',
    category: 'printers',
    brand: 'Brother',
    price: 14800,
    image: 'https://content1.rozetka.com.ua/goods/images/big/384768526.jpg',
    description: 'Швидкий кольоровий лазерний принтер для бізнесу. 31 стор/хв кольорового друку, автоматичний двосторонній, Wi-Fi, NFC.',
    inStock: false,
    colorPrint: true,
    wireless: true,
    laser: true,
    duplex: true,
    a4: true,
    maxDpi: 2400,
  },
  {
    id: 'p005',
    name: 'Canon Pixma iP8740',
    category: 'printers',
    brand: 'Canon',
    price: 7900,
    image: 'https://cdn.comfy.ua/media/catalog/product/cache/5/image/600x/9df78eab33525d08d6e5fb8d27136e95/4/7/47414655.jpg',
    description: 'Струменевий фотопринтер для друку у форматі A3+.',
    inStock: true, colorPrint: true, wireless: true, inkjet: true, a3: true, a4: true, maxDpi: 9600,
  },
  {
    id: 'p006',
    name: 'Xerox Phaser 3020BI',
    category: 'printers',
    brand: 'Xerox',
    price: 4300,
    image: 'https://cdn.comfy.ua/media/catalog/product/cache/5/image/600x/9df78eab33525d08d6e5fb8d27136e95/x/e/xerox_3020bi_wi-fi_2_1.jpg',
    description: 'Надійний лазерний принтер для дому та навчання.',
    inStock: true, wireless: true, laser: true, a4: true, maxDpi: 1200,
  },
  {
    id: 'p007',
    name: 'Epson SureColor SC-P700',
    category: 'printers',
    brand: 'Epson',
    price: 29500,
    image: 'https://content2.rozetka.com.ua/goods/images/big/14033360.jpg',
    description: 'Професійний фотопринтер для галерейної якості друку.',
    inStock: true, colorPrint: true, wireless: true, inkjet: true, a3: true, a4: true, maxDpi: 5760,
  },
  {
    id: 'p008',
    name: 'HP LaserJet Pro M15w',
    category: 'printers',
    brand: 'HP',
    price: 3800,
    image: 'https://content.rozetka.com.ua/goods/images/big/329416560.jpg',
    description: 'Найменший у класі лазерний принтер з Wi-Fi.',
    inStock: true, wireless: true, laser: true, a4: true, maxDpi: 600,
  },
  {
    id: 'p009',
    name: 'Canon imagePROGRAF PRO-300',
    category: 'printers',
    brand: 'Canon',
    price: 32000,
    image: 'https://cdn.comfy.ua/media/catalog/product/cache/5/image/600x/9df78eab33525d08d6e5fb8d27136e95/i/m/imageprograf-pro-310_gallery_02_b2c86bff619944eebf6d85dcb05c9092.jpg',
    description: 'Професійний 10-колірний фотопринтер формату A3+.',
    inStock: false, colorPrint: true, wireless: true, inkjet: true, a3: true, a4: true, maxDpi: 4800,
  },
  {
    id: 'p010',
    name: 'Brother HL-L5100DN',
    category: 'printers',
    brand: 'Brother',
    price: 11500,
    image: 'https://content2.rozetka.com.ua/goods/images/big/442164653.jpg',
    description: 'Високошвидкісний лазерний принтер для великих обсягів.',
    inStock: true, laser: true, duplex: true, a4: true, maxDpi: 1200,
  },
  {
    id: 'p011',
    name: 'Epson EcoTank L1210',
    category: 'printers',
    brand: 'Epson',
    price: 5900,
    image: 'https://content.rozetka.com.ua/goods/images/big/321459104.jpg',
    description: 'Надійний принтер з безперервною подачею чорнила.',
    inStock: true, colorPrint: true, inkjet: true, a4: true, maxDpi: 5760,
  },
  {
    id: 'p012',
    name: 'HP LaserJet Pro M203dn',
    category: 'printers',
    brand: 'HP',
    price: 7500,
    image: 'https://cdn.comfy.ua/media/catalog/product/cache/5/image/600x/9df78eab33525d08d6e5fb8d27136e95/h/p/hp_laserjet_pro_3003dn_3g653a_3_.jpg',
    description: 'Офісний лазерний принтер з автоматичним двостороннійом.',
    inStock: true, laser: true, duplex: true, a3: false, a4: true, maxDpi: 1200,
  },
  {
    id: 'p013',
    name: 'Canon Pixma G1420',
    category: 'printers',
    brand: 'Canon',
    price: 6500,
    image: 'https://content.rozetka.com.ua/goods/images/big/430011976.jpg',
    description: 'Простий та економічний принтер для домашнього друку.',
    inStock: false, colorPrint: true, inkjet: true, a4: true, maxDpi: 4800,
  },
  {
    id: 'p014',
    name: 'Brother HL-L6400DW',
    category: 'printers',
    brand: 'Brother',
    price: 34500,
    image: 'https://content1.rozetka.com.ua/goods/images/big/209438437.jpg',
    description: 'Професійний лазерний принтер для корпоративного друку.',
    inStock: true, wireless: true, inkjet: false, laser: true, duplex: true, a4: true, a5: true, maxDpi: 1200,
  },
  {
    id: 'p015',
    name: 'Epson Expression Photo XP-55',
    category: 'printers',
    brand: 'Epson',
    price: 6800,
    image: 'https://lucky-print.com.ua/uploaded/img/shop/16877/epson-xp-55-3.jpg?width=1000',
    description: '6-колірний фотопринтер для якісного друку фотографій.',
    inStock: true, colorPrint: true, wireless: true, inkjet: true, laser: false, duplex: true, a4: true, maxDpi: 5760,
  },
  {
    id: 'p016',
    name: 'HP LaserJet Enterprise M507dn',
    category: 'printers',
    brand: 'HP',
    price: 24000,
    image: 'https://cdn.comfy.ua/media/catalog/product/cache/5/image/600x/9df78eab33525d08d6e5fb8d27136e95/j/8/j8h61a_3.jpg',
    description: 'Потужний лазерний принтер для підприємств.',
    inStock: true, laser: true, duplex: true, a4: true, a5: true, maxDpi: 1200,
  },
  {
    id: 'p017',
    name: 'Canon Pixma G540',
    category: 'printers',
    brand: 'Canon',
    price: 10200,
    image: 'https://cdn.media.amplience.net/i/canon/pixma-g550-fsl_gallery_04_a0dd93d50cfb4cf896f4c2c8572849fa?$prod-spec-hero-1by1$',
    description: '6-колірний принтер для якісного фотодруку з низькою собівартістю.',
    inStock: true, colorPrint: true, wireless: true, inkjet: true, a4: true, a5: true, maxDpi: 4800,
  },
  {
    id: 'p018',
    name: 'Brother HL-L2375DW',
    category: 'printers',
    brand: 'Brother',
    price: 6100,
    image: 'https://content2.rozetka.com.ua/goods/images/big/384768518.jpg',
    description: 'Надійний монохромний лазерний принтер з Wi-Fi та Ethernet.',
    inStock: true, colorPrint: false, wireless: true, inkjet: false, laser: true, duplex: true, a3: false, a4: true, maxDpi: 2400,
  },
  {
    id: 'p019',
    name: 'Epson EcoTank L8050',
    category: 'printers',
    brand: 'Epson',
    price: 14200,
    image: 'https://www.inksystem.biz/uploaded/img/shop/18760/epson-l8050-01-min.jpg?width=1000',
    description: 'Фотопринтер для професіоналів з системою EcoTank.',
    inStock: true, colorPrint: true, wireless: true, inkjet: true, laser: false, duplex: false, a3: false, a4: true, a5: true, maxDpi: 5760,
  },
  {
    id: 'p020',
    name: 'HP LaserJet Pro M404n',
    category: 'printers',
    brand: 'HP',
    price: 8400,
    image: 'https://eurocopy.ua/uploads/thumb/7018/product_galleryImage/35094133-product-Printer-HP-LaserJet-Pro-M404n-W1A52A-_24994104b51bd3c3ec716b6e453e9b32.jpg',
    description: 'Лазерний принтер для ефективної роботи в офісі.',
    inStock: true, colorPrint: false, wireless: false, inkjet: false, laser: true, duplex: false, a3: false, a4: true, maxDpi: 1200,
  },
  { id: 'p021', name: 'Canon i-SENSYS LBP6030B', category: 'printers', brand: 'Canon', price: 5200, image: 'https://mobileplanet.ua/uploads/small_photos/2025-9-29/canon-i-sensys-lbp6030b-8468b006-ua-357670_1.webp', description: 'Компактний лазерний принтер для дому.', inStock: true, laser: true, a4: true },
  { id: 'p022', name: 'Brother HL-L2350DW', category: 'printers', brand: 'Brother', price: 6800, image: 'https://luckylink.kiev.ua/image/catalog/product/182/34/product_image_66734_153611.jpg', description: 'Швидкий лазерний принтер з Wi-Fi та двостороннійом.', inStock: true, laser: true, wireless: true, duplex: true, a4: true },
  { id: 'p026', name: 'Brother HL-T4000DW', category: 'printers', brand: 'Brother', price: 14500, image: 'https://m.media-amazon.com/images/I/61AcfvioCgL._AC_UF1000,1000_QL80_.jpg', description: 'Кольоровий струменевий принтер формату A3.', inStock: true, colorPrint: true, inkjet: true, wireless: true, duplex: true, a3: true },
  { id: 'p027', name: 'Epson WorkForce WF-7710', category: 'printers', brand: 'Epson', price: 12000, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJr9P9518ZCPnksU451aF41IuHmtcF3XXUeg&s', description: 'Потужний струменевий принтер для офісу.', inStock: true, colorPrint: true, inkjet: true, wireless: true, duplex: true, a3: true },
  { id: 'p028', name: 'HP Color LaserJet Pro M255dw', category: 'printers', brand: 'HP', price: 13500, image: 'https://content.secur.ua/goods/images/big/A6LQvZhwPWIHh42ZxFF0MnoptoNT82XiJHDfE4yI.webp', description: 'Кольоровий лазерний принтер з високою швидкістю.', inStock: true, colorPrint: true, laser: true, wireless: true, duplex: true, a4: true },
  { id: 'p029', name: 'Canon LBP223dw', category: 'printers', brand: 'Canon', price: 9200, image: 'https://dzvinok.ua/pub/media/catalog/product/cache/0940dbeaa525ae9ef67299dfbda6a8bb/2/5/2540589.jpeg', description: 'Високопродуктивний офісний лазерний принтер.', inStock: true, laser: true, wireless: true, duplex: true, a4: true },

  // === SCANNERS ===
  {
    id: 's001',
    name: 'Epson Perfection V39 Планшетний',
    category: 'scanners',
    brand: 'Epson',
    price: 3200,
    image: 'https://e.428.ua/img/4102150/3000/2000/skaner_epson_perfection_v39ii_b11b268401~1029~585.jpg',
    description: 'Компактний планшетний сканер A4 з роздільною здатністю 4800 dpi. Підходить для сканування документів, фото та слайдів. Підключення USB.',
    inStock: true,
    portableScanner: false,
    autoFeed: false,
    maxDpi: 4800,
  },
  {
    id: 's002',
    name: 'Canon DR-C230 Документний з автоподачею',
    category: 'scanners',
    brand: 'Canon',
    price: 12900,
    image: 'https://content2.rozetka.com.ua/goods/images/big/404087784.jpg',
    description: 'Офісний документний сканер з автоподачею до 60 аркушів. Двостороннє сканування, 30 стор/хв, підключення USB 3.1.',
    inStock: true,
    portableScanner: false,
    autoFeed: true,
    maxDpi: 600,
  },
  {
    id: 's003',
    name: 'Brother ADS-1200 Портативний',
    category: 'scanners',
    brand: 'Brother',
    price: 5800,
    image: 'https://content2.rozetka.com.ua/goods/images/big/442153884.jpg',
    description: 'Компактний портативний сканер з автоподачею. Живлення від USB, ідеальний для роботи в дорозі. 25 стор/хв, двостороннє сканування.',
    inStock: true,
    portableScanner: true,
    autoFeed: true,
    maxDpi: 600,
  },
  {
    id: 's004',
    name: 'Canon imageFORMULA DR-C225 II',
    category: 'scanners',
    brand: 'Canon',
    price: 18500,
    image: 'https://i.can.ua/goods/4822/4822561.jpg',
    description: 'Високошвидкісний компактний потоковий сканер. Ідеальний для офісів, що потребують швидкої оцифровки документів.',
    inStock: true,
    autoFeed: true,
    duplex: true,
    maxDpi: 600,
  },
  {
    id: 's005',
    name: 'Brother ADS-2200 Desktop Scanner',
    category: 'scanners',
    brand: 'Brother',
    price: 12900,
    image: 'https://i.pcmag.com/imagery/reviews/03xgjzbNgCuBx3c9mJF0p8p-6.fit_lim.size_1050x591.v1569472297.jpg',
    description: 'Надійний сканер для робочих груп. Простота використання та висока якість зображення.',
    inStock: false,
    autoFeed: true,
    maxDpi: 1200,
  },
  {
    id: 's006',
    name: 'Fujitsu ScanSnap iX1600 Wireless',
    category: 'scanners',
    brand: 'Fujitsu',
    price: 24500,
    image: 'https://m.media-amazon.com/images/I/71ANAigae8L._AC_UF1000,1000_QL80_.jpg',
    description: 'Легендарний сканер з Wi-Fi та сенсорним екраном. Перетворює паперові документи на цифрові за лічені секунди.',
    inStock: true,
    autoFeed: true,
    wireless: true,
    duplex: true,
  },
  {
    id: 's007',
    name: 'Epson WorkForce DS-310 Portable',
    category: 'scanners',
    brand: 'Epson',
    price: 8900,
    image: 'https://sm.pcmag.com/t/pcmag_uk/review/e/epson-work/epson-workforce-es-300wr-wireless-document-scanner-accountin_ajba.1200.jpg',
    description: 'Найшвидший портативний сканер у своєму класі. Живлення від USB.',
    inStock: true,
    portableScanner: true,
    maxDpi: 600,
  },
  {
    id: 's008',
    name: 'Plustek ePhoto Z300 Photo Scanner',
    category: 'scanners',
    brand: 'Plustek',
    price: 6500,
    image: 'https://copyfaxes.com/media/p/o/441f3e64_Plustek_ePhoto_Z300.jpg',
    description: 'Спеціалізований сканер для фотографій. Жодних планшетів, просто подача фото.',
    inStock: true,
    maxDpi: 600,
  },
  {
    id: 's009',
    name: 'HP ScanJet Pro 2600 f1',
    category: 'scanners',
    brand: 'HP',
    price: 14200,
    image: 'https://i.can.ua/images/650x650/goods/11560/11560149.jpg',
    description: 'Планшетний сканер з автоподавачем документів. Професійне рішення для документообігу.',
    inStock: false,
    autoFeed: true,
    duplex: true,
  },
  {
    id: 's010',
    name: 'Xerox DocuMate 3125',
    category: 'scanners',
    brand: 'Xerox',
    price: 15600,
    image: 'https://i.ebayimg.com/images/g/hSoAAOSwNGpm2FxV/s-l1600.webp',
    description: 'Компактний, швидкий та надійний сканер для щоденних офісних завдань.',
    inStock: true,
    autoFeed: true,
    duplex: true,
  },
  {
    id: 's011',
    name: 'Brother DS-940DW Mobile',
    category: 'scanners',
    brand: 'Brother',
    price: 7200,
    image: 'https://sm.pcmag.com/pcmag_au/review/b/brother-ds/brother-dsmobile-ds-940dw-review_jmkv.jpg',
    description: 'Мобільний сканер з вбудованим акумулятором та Wi-Fi. Скануйте будь-де.',
    inStock: true,
    portableScanner: true,
    wireless: true,
  },
  {
    id: 's012',
    name: 'Fujitsu fi-8170 Production Scanner',
    category: 'scanners',
    brand: 'Fujitsu',
    price: 58000,
    image: 'https://www.pfu-emea.ricoh.com/_assets/images/asset_images/img_fi-8170_overview02_ver2_tcm100-6451998_tcm100-2750236-32.jpg',
    description: 'Високопродуктивний сканер для архівів та великих обсягів документів.',
    inStock: true,
    autoFeed: true,
    duplex: true,
    maxDpi: 600,
  },
  {
    id: 's013',
    name: 'Canon CanoScan LiDE 400',
    category: 'scanners',
    brand: 'Canon',
    price: 3400,
    image: 'https://content1.rozetka.com.ua/goods/images/big/8932732.jpg',
    description: 'Тонкий планшетний сканер. Ідеальний для дому та студентів.',
    inStock: false,
    maxDpi: 4800,
  },
  {
    id: 's014',
    name: 'Epson Perfection V850 Pro',
    category: 'scanners',
    brand: 'Epson',
    price: 38000,
    image: 'https://magazun.com/images/detailed/380/3_071f3727-593c-11ea-a232-7085c2a4485b.jpg',
    description: 'Сканер преміум-класу для фотографів та професіоналів. Сканування слайдів та негативів.',
    inStock: true,
    maxDpi: 9600,
  },
  {
    id: 's015',
    name: 'IRIScan Anywhere 6',
    category: 'scanners',
    brand: 'IRIS',
    price: 5200,
    image: 'https://i.allo.ua/media/catalog/product/cache/1/image/710x600/602f0fa2c1f0d1ba5e241f914e856ff9/import/5455041118480774.webp',
    description: 'Автономний портативний сканер з можливістю запису на SD-карту.',
    inStock: true,
    portableScanner: true,
  },
  {
    id: 's016',
    name: 'HP ScanJet Enterprise Flow 7000',
    category: 'scanners',
    brand: 'HP',
    price: 22000,
    image: 'https://cdn.27.ua/799/d6/88/448136_3.jpeg',
    description: 'Для великих офісів. Швидке двостороннє сканування.',
    inStock: true,
    autoFeed: true,
    duplex: true,
  },
  {
    id: 's017',
    name: 'Kodak Alaris E1035',
    category: 'scanners',
    brand: 'Kodak',
    price: 19500,
    image: 'https://lh6.googleusercontent.com/proxy/tXF0fvF_teVGTRyu6l4_0UNZqFWk4I-tgn3rjVHN_tYb2eYJ1X4PJAPgyZqfUQmE4Kr_6PwsgqZKm9YBto9gECwImAp8G99OYvcWx7Kzf24B5jJahEhML0yxjdHxJFUhQXWRUOBGH30yVEB0T0bOQbZnI1ryqve7Nyi5vJOpofR_ob0pwIWGwi2C8dyHHE5Nfa48jJgD_7XXEi49UhNH8DGhsufp1xpaiRSavIpJVue8bzDI3lmxNw',
    description: 'Робоча конячка для бізнес-документів.',
    inStock: false,
    autoFeed: true,
    duplex: true,
  },
  {
    id: 's018',
    name: 'Brother ADS-4300N',
    category: 'scanners',
    brand: 'Brother',
    price: 16800,
    image: 'https://content1.rozetka.com.ua/goods/images/big/384795592.jpg',
    description: 'Мережевий сканер з підтримкою Ethernet для спільної роботи.',
    inStock: true,
    autoFeed: true,
    duplex: true,
  },
  {
    id: 's019',
    name: 'Fujitsu ScanSnap SV600',
    category: 'scanners',
    brand: 'Fujitsu',
    price: 31000,
    image: 'https://wwm.ua/media/catalog/product/cache/366eaab42af7c91e55d01fc221896c68/N/0/N0_9312.webp',
    description: 'Безконтактний сканер. Сканує документи, не торкаючись їх.',
    inStock: true,
    maxDpi: 1200,
  },
  {
    id: 's020',
    name: 'Epson FastFoto FF-680W',
    category: 'scanners',
    brand: 'Epson',
    price: 21500,
    image: 'https://robby.com.ua/image/catalog/tovar/files/epson-fastfoto-ff680w/Epson_B11B237401_2.jpg',
    description: 'Найшвидший у світі сканер для фотографій.',
    inStock: true,
    autoFeed: true,
    wireless: true,
  },
  {
    id: 's021',
    name: 'Canon imageFORMULA P-215II',
    category: 'scanners',
    brand: 'Canon',
    price: 9800,
    image: 'https://content1.rozetka.com.ua/goods/images/big/16749488.jpg',
    description: 'Популярний портативний сканер для офісних поїздок.',
    inStock: false,
    portableScanner: true,
    duplex: true,
  },
  {
    id: 's022',
    name: 'Xerox D35',
    category: 'scanners',
    brand: 'Xerox',
    price: 13500,
    image: 'https://www.xerographic.com.cy/wp-content/uploads/sites/65/2023/12/xerox-d35-scanner-en.png',
    description: 'Професійний потоковий сканер для інтенсивної роботи.',
    inStock: true,
    autoFeed: true,
    duplex: true,
  },
  {
    id: 's023',
    name: 'Plustek SmartOffice PS306',
    category: 'scanners',
    brand: 'Plustek',
    price: 11200,
    image: 'https://cdn.x-kom.pl/i/setup/images/prod/big/product-new-big,,2018/1/pr_2018_1_11_14_1_41_367_00.jpg',
    description: 'Економічне рішення для оцифровки документів у середньому офісі.',
    inStock: true,
    autoFeed: true,
  },

  // === MFP (Багатофункціональні пристрої) ===
  {
    id: 'm001',
    name: 'HP Color LaserJet Pro MFP M479fdw',
    category: 'mfp',
    brand: 'HP',
    price: 21500,
    image: 'https://allegro.stati.pl/AllegroIMG/PRODUCENCI/HP/W1A80A/HP_W1A80A_2.jpg',
    description: 'Кольоровий лазерний БФП з факсом, Wi-Fi, двостороннійом та сенсорним дисплеєм. Друк, копіювання, сканування, факс в одному пристрої.',
    inStock: true,
    colorPrint: true,
    wireless: true,
    laser: true,
    duplex: true,
    touchScreen: true,
    autoFeed: true,
  },
  {
    id: 'm002',
    name: 'Epson EcoTank ET-5850 Струменевий БФП',
    category: 'mfp',
    brand: 'Epson',
    price: 16200,
    image: 'https://content1.rozetka.com.ua/goods/images/big_tile/410897257.jpg',
    description: 'Струменевий БФП з безперервною подачею чорнила, Wi-Fi, автоподавачем документів. Надзвичайно низька вартість сторінки.',
    inStock: true,
    colorPrint: true,
    wireless: true,
    inkjet: true,
    duplex: true,
    touchScreen: true,
    autoFeed: true,
  },
  {
    id: 'm003',
    name: 'Canon i-SENSYS MF445dw Монохромний БФП',
    category: 'mfp',
    brand: 'Canon',
    price: 11800,
    image: 'https://defis.ua/image/cache/catalog/2/23/23644_5-500x500.jpg',
    description: 'Монохромний лазерний БФП для малого бізнесу. 38 стор/хв, Wi-Fi, двосторонній, автоподавач 50 аркушів.',
    inStock: true,
    wireless: true,
    laser: true,
    duplex: true,
    autoFeed: true,
  },
  {
    id: 'm004',
    name: 'Canon PIXMA TR4640 Струменевий',
    category: 'mfp',
    brand: 'Canon',
    price: 3800,
    image: 'https://i.citrus.world/imgcache/size_800/uploads/shop/1/6/1697793265-opt.webp',
    description: 'Компактний БФП для дому. Підтримка друку зі смартфона через Wi-Fi.',
    inStock: true,
    colorPrint: true,
    wireless: true,
    inkjet: true,
    autoFeed: true,
  },
  {
    id: 'm005',
    name: 'Brother DCP-L2540DNR Лазерний',
    category: 'mfp',
    brand: 'Brother',
    price: 9500,
    image: 'https://dolyna.in.ua/image/cache/import_files/002690306_0.-600x600.jpg',
    description: 'Надійний монохромний лазерний БФП з мережевим підключенням.',
    //  tags: [{ label: 'Бренд', value: 'Brother' }],
    inStock: false,
    laser: true,
    duplex: true,
  },
  {
    id: 'm006',
    name: 'Epson EcoTank L4260',
    category: 'mfp',
    brand: 'Epson',
    price: 11200,
    image: 'https://b.428.ua/img/4037743/3000/2000/mfu_struynoe_epson_ecotank_l4260_c11cj63412~1168~800.jpg',
    description: 'БФП з системою безперервної подачі чорнила. Економний друк.',
    //  tags: [{ label: 'Бренд', value: 'Epson' }],
    inStock: true,
    colorPrint: true,
    wireless: true,
    inkjet: true,
    duplex: true,
  },
  {
    id: 'm007',
    name: 'HP LaserJet Pro MFP M227fdw',
    category: 'mfp',
    brand: 'HP',
    price: 13500,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0ZMy2tqa38ua2NfxPi5XMTwletn11g8UTcg&s',
    description: 'Багатофункціональний лазерний пристрій для малого офісу.',
    //  tags: [{ label: 'Бренд', value: 'HP' }],
    inStock: true,
    laser: true,
    wireless: true,
    duplex: true,
    touchScreen: true,
    autoFeed: true,
  },
  {
    id: 'm008',
    name: 'Xerox WorkCentre 3025BI',
    category: 'mfp',
    brand: 'Xerox',
    price: 7800,
    image: 'https://f.428.ua/img/406721/3000/2000/mfu_lazernoe_xerox_workcentre_3025bi_3025v_bi~740~568.jpg',
    description: 'Компактний лазерний БФП, ідеальний для персонального використання.',
    //  tags: [{ label: 'Бренд', value: 'Xerox' }],
    inStock: true,
    laser: true,
    wireless: true,
  },
  {
    id: 'm009',
    name: 'Canon i-SENSYS MF655Cdw',
    category: 'mfp',
    brand: 'Canon',
    price: 19500,
    image: 'https://images.prom.ua/7143408123_w300_h300_printer-canon-i-sensys.jpg',
    description: 'Кольоровий лазерний БФП. Висока швидкість та якість друку.',
    //  tags: [{ label: 'Бренд', value: 'Canon' }],
    inStock: false,
    colorPrint: true,
    laser: true,
    wireless: true,
    touchScreen: true,
  },
  {
    id: 'm010',
    name: 'Brother MFC-L8690CDW',
    category: 'mfp',
    brand: 'Brother',
    price: 28000,
    image: 'https://content2.rozetka.com.ua/goods/images/big/497338717.jpg',
    description: 'Професійний кольоровий лазерний БФП для інтенсивної роботи.',
    //  tags: [{ label: 'Бренд', value: 'Brother' }],
    inStock: true,
    colorPrint: true,
    laser: true,
    duplex: true,
    autoFeed: true,
    touchScreen: true,
  },
  {
    id: 'm011',
    name: 'Epson WorkForce Pro WF-C5790',
    category: 'mfp',
    brand: 'Epson',
    price: 15000,
    image: 'https://www.inksystem.biz/uploaded/img/shop/15342/c5790dwf-1-min.jpg',
    description: 'Високошвидкісний струменевий БФП для великих обсягів.',
    inStock: true,
    colorPrint: true,
    inkjet: true,
    duplex: true,
    touchScreen: true,
  },
  {
    id: 'm012',
    name: 'HP Color LaserJet Pro MFP M283fdw',
    category: 'mfp',
    brand: 'HP',
    price: 18900,
    image: 'https://gfx3.senetic.com/akeneo-catalog/3/d/1/9/3d1923d40e36259f14be94e83932d2779eb14b8f_1650540_7KW75A_B19_image3.jpg',
    description: 'Універсальний кольоровий лазерний БФП.',
    inStock: false,
    colorPrint: true,
    laser: true,
    wireless: true,
    autoFeed: true,
  },
  {
    id: 'm013',
    name: 'Kyocera ECOSYS M5526cdw',
    category: 'mfp',
    brand: 'Kyocera',
    price: 24000,
    image: 'https://wwm.ua/media/catalog/product/cache/366eaab42af7c91e55d01fc221896c68/m/f/mfu-a4-kyocera-mita-ecosys-m5526cdw-1102r73nl0_2.webp',
    description: 'Надійний кольоровий БФП з низькою вартістю володіння.',
    inStock: false,
    colorPrint: true,
    laser: true,
    wireless: true,
    duplex: true,
  },
  {
    id: 'm014',
    name: 'Canon PIXMA G6040',
    category: 'mfp',
    brand: 'Canon',
    price: 8500,
    image: 'https://content.rozetka.com.ua/goods/images/big_tile/15467545.jpg',
    description: 'Економний БФП з великими резервуарами чорнил.',
    inStock: true,
    colorPrint: true,
    inkjet: true,
    wireless: true,
  },
  {
    id: 'm015',
    name: 'Brother DCP-1610W',
    category: 'mfp',
    brand: 'Brother',
    price: 5200,
    image: 'https://rt6.co.za/wp-content/uploads/1610W-Feature.png',
    description: 'Доступний лазерний БФП з Wi-Fi.',
    inStock: true,
    laser: true,
    wireless: true,
  },
  {
    id: 'm016',
    name: 'HP LaserJet Tank MFP 2604sdw',
    category: 'mfp',
    brand: 'HP',
    price: 12500,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhZ-zqfqET7FPi5B-edWTKLb4RgSYEl-kDPg&s',
    description: 'Лазерний БФП з можливістю легкої заправки тонера.',
    inStock: true,
    laser: true,
    wireless: true,
    duplex: true,
  },
  {
    id: 'm017',
    name: 'Xerox B225',
    category: 'mfp',
    brand: 'Xerox',
    price: 9900,
    image: 'https://crdms.images.consumerreports.org/f_auto,w_1200/prod/products/cr/models/407618-all-in-one-black-and-white-laser-printers-xerox-b225-dni-10033103.png',
    description: 'Надійний монохромний БФП для офісу.',
    inStock: false,
    laser: true,
    wireless: true,
  },
  {
    id: 'm018',
    name: 'Epson EcoTank L6270',
    category: 'mfp',
    brand: 'Epson',
    price: 13800,
    image: 'https://touch.com.ua/upload/iblock/901/hosbxt0hovc5et42v9rweodt578pth5l.jpg',
    description: 'Струменевий БФП з автоподавачем та Wi-Fi.',
    inStock: true,
    colorPrint: true,
    inkjet: true,
    autoFeed: true,
    duplex: true,
  },
  {
    id: 'm019',
    name: 'Canon i-SENSYS MF455dw',
    category: 'mfp',
    brand: 'Canon',
    price: 17500,
    image: 'https://kopirka.by/upload/iblock/657/lrsgkd77lg7wemao9iga76zbz7mmcefo/d6057b09_3032_11ee_b88a_000c29d36873_5b7875a2_010e_11f1_b020_000c29754cdb.jpg',
    description: 'Швидкий монохромний лазерний БФП.',
    inStock: true,
    laser: true,
    duplex: true,
    touchScreen: true,
  },
  {
    id: 'm020',
    name: 'Brother MFC-J6940DW',
    category: 'mfp',
    brand: 'Brother',
    price: 22500,
    image: 'https://ik.imagekit.io/pimberly/595e406f0f15f30010780448/b6d00aaf/62613f4a423ec079390001ed/BA81442_02.jpg?tr=w-1500,h-1500,cm-pad_resize,bg-FFFFFF',
    description: 'Професійний БФП формату A3.',
    inStock: true,
    colorPrint: true,
    inkjet: true,
    a3: true,
  },
  {
    id: 'm021',
    name: 'Kyocera ECOSYS M2040dn',
    category: 'mfp',
    brand: 'Kyocera',
    price: 14200,
    image: 'https://api.e-server.com.ua/storage/205323/rs/U0223436_4big___rs_1200_1200.jpg',
    description: 'Високопродуктивний офісний БФП.',
    inStock: true,
    laser: true,
    autoFeed: true,
  },
  {
    id: 'm022',
    name: 'HP OfficeJet Pro 9010',
    category: 'mfp',
    brand: 'HP',
    price: 8800,
    image: 'https://media.ldlc.com/r1600/ld/products/00/05/82/92/LD0005829226_1.jpg',
    description: 'Розумний БФП для продуктивної роботи.',
    inStock: false,
    colorPrint: true,
    inkjet: true,
    wireless: true,
  },
  {
    id: 'm023',
    name: 'Xerox VersaLink B405',
    category: 'mfp',
    brand: 'Xerox',
    price: 32000,
    image: 'https://www.ops.com.ua/files/resized/products/b405-openlot-800x800.1800x1800w.jpg',
    description: 'Потужний офісний БФП корпоративного класу.',
    inStock: true,
    laser: true,
    touchScreen: true,
    duplex: true,
  },

  // === INK (Чорнила) ===
  {
    id: 'i001',
    name: 'Epson 103 EcoTank Чорнило Чорне 65мл',
    category: 'ink',
    brand: 'Epson',
    price: 320,
    image: 'https://www.inksystem.biz/uploaded/img/shop/16019/epson-ink-103-black-min.jpg?width=1000',
    description: 'Оригінальне чорне чорнило для принтерів серії EcoTank. Об\'єм 65 мл, висока стійкість до вигоряння, насичений чорний колір.',
    inStock: true,
    oem: true,
  },
  {
    id: 'i002',
    name: 'Canon GI-490 Заправне чорнило Cyan 70мл',
    category: 'ink',
    brand: 'Canon',
    price: 380,
    image: 'https://img9.itbox.ua/700x700/prod_img/9/U0167139_1719922981.webp',
    description: 'Оригінальне чорнило Cyan для серії PIXMA G. 70 мл, понад 7000 сторінок при 5% заповненні.',
    inStock: true,
    oem: true,
  },
  {
    id: 'i003',
    name: 'ColorWay Сумісне чорнило для HP 100мл Magenta',
    category: 'ink',
    brand: 'ColorWay',
    price: 180,
    image: 'https://img6.itbox.ua/700x700/prod_img/6/U0251646_1720018228.webp',
    description: 'Сумісне чорнило для принтерів HP. 100 мл, збалансований колір, стійкий до вигоряння. Відмінне співвідношення ціна/якість.',
    inStock: true,
    refill: true,
  },
  {
    id: 'i004',
    name: 'Brother LC3213 Набір чорнил 4 кольори',
    category: 'ink',
    brand: 'Brother',
    price: 890,
    image: 'https://images.prom.ua/7140261973_w640_h640_komplekt-kartridzhej-4.jpg',
    description: 'Оригінальний набір із 4 картриджів: чорний, блакитний, пурпурний, жовтий. Для принтерів Brother MFC і DCP.',
    inStock: true,
    oem: true,
  },
  //  (oem: true)
  { id: 'i005', name: 'Epson 103 (C13T00S14A) Чорне', category: 'ink', brand: 'Epson', price: 210, image: 'https://img4.itbox.ua/700x700/prod_img/4/U0335964_1720114795.webp', description: 'Оригінальний флакон чорного чорнила.', inStock: true, oem: true, isBulk: true },
  { id: 'i006', name: 'HP GT53XL Чорне (1VV21AE)', category: 'ink', brand: 'HP', price: 280, image: 'https://lucky-print.com.ua/uploaded/img/shop/17296/ink-hp-black-135ml-gt53xl-min.png?width=1000', description: 'Оригінальне чорнило для HP Tank.', inStock: true, oem: true, isBulk: true },
  { id: 'i007', name: 'Canon GI-41 PGBK', category: 'ink', brand: 'Canon', price: 320, image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSuzJKGOAMAxYkoN56VOw9ucBerYiILnhxVZq7HrTRs0SDfW6c_oXCIOvTVTderXHE8q_D2dw4uZ2JfarLRoL3apSEDWS2G_athrVF1zprQJTV3JisD1-tOE_kgL-PDdG8hG3ca-30&usqp=CAc', description: 'Пігментне чорне чорнило Canon.', inStock: true, oem: true, isBulk: true },
  { id: 'i008', name: 'Brother LC422 Набір XL', category: 'ink', brand: 'Brother', price: 2400, image: 'https://ae-pic-a1.aliexpress-media.com/kf/Se4e3d2da6a3d444bb38c8fc7965dfce9C.jpg_960x960q75.jpg_.avif', description: 'Набір картриджів підвищеної ємності.', oem: true },
  { id: 'i009', name: 'Canon CLI-481 Набір', category: 'ink', brand: 'Canon', price: 1800, image: 'https://p.ua/media/catalog/product/cache/e97bfe48fc3322ec3691b281a1a6a88d/k/o/komplekt-chernil-wwm-c45set-5.webp', description: 'Оригінальний набір картриджів для фотодруку.', inStock: true, oem: true },
  { id: 'i010', name: 'Epson 664 Набір 4 кольори', category: 'ink', brand: 'Epson', price: 850, image: 'https://fotoink.com.ua/image/cache/catalog/image/cache/catalog/data/epson/epson-664-chernil-700x700.webp', description: 'Економний набір для серії L.', inStock: true, oem: true, isBulk: true },
  { id: 'i011', name: 'HP 305 Black', category: 'ink', brand: 'HP', price: 450, image: 'https://hp.widen.net/content/bkkjr4of5n/png/bkkjr4of5n.png?w=800&h=600&dpi=72&color=ffffff00', description: 'Картридж чорний.', inStock: true, oem: true },
  { id: 'i012', name: 'Brother LC3211 Cyan', category: 'ink', brand: 'Brother', price: 390, image: 'https://inkjetworld.ie/wp-content/uploads/2021/02/100e4094-d79c-42ed-a9cc-fd79cb333983.jpeg', description: 'Блакитний картридж.', inStock: true, oem: true },
  { id: 'i013', name: 'Epson 104 Yellow', category: 'ink', brand: 'Epson', price: 190, image: 'https://img6.itbox.ua/700x700/prod_img/6/U0344516_1720122639.webp', description: 'Жовте чорнило для СБПЧ.', oem: true, isBulk: true },
  { id: 'i014', name: 'Canon PG-460 Black', category: 'ink', brand: 'Canon', price: 400, image: 'https://content.rozetka.com.ua/goods/images/big/168194874.jpg', description: 'Преміум чорне чорнило.', inStock: true, oem: true, isBulk: true },
  //  (refill: true)
  { id: 'i015', name: 'ColorWay для Epson (Набір)', category: 'ink', brand: 'Epson', price: 450, image: 'https://fotoink.com.ua/image/cache/catalog/image/cache/catalog/data/CW-NEW/cw-ew650-700x700.webp', description: 'Сумісне чорнило для багатьох моделей.', inStock: true, refill: true, isBulk: true },
  { id: 'i016', name: 'WWM для Canon (Набір)', category: 'ink', brand: 'Canon', price: 480, image: 'https://cdn.27.ua/sc--media--prod/default/db/ba/73/dbba739c-ace8-4bac-84fe-41d0f0b7f6d9.jpg', description: 'Набір сумісного чорнила.', inStock: true, refill: true, isBulk: true },
  { id: 'i017', name: 'Patron для HP (Black)', category: 'ink', brand: 'HP', price: 120, image: 'https://p.ua/media/catalog/product/cache/e97bfe48fc3322ec3691b281a1a6a88d/h/3/h30-bp-chernila-kraska-black-chernyj-pigmentnye-200g.webp', description: 'Аналог HP чорний.', inStock: true, refill: true, isBulk: true },
  { id: 'i018', name: 'Barva для Brother (Набір)', category: 'ink', brand: 'Brother', price: 350, image: 'https://prote.ua/storage/media/products/111306/af530bf82461e7062.webp', description: 'Бюджетний варіант.', refill: true, isBulk: true },
  { id: 'i019', name: 'Lucky Print для Epson', category: 'ink', brand: 'Epson', price: 200, image: 'https://fotoink.com.ua/image/cache/catalog/image/catalog/data/Lucky%20Print%20/E62763-68.webp', description: 'Фоточорнило.', inStock: true, refill: true, isBulk: true },
  { id: 'i020', name: 'Inksystem Canon Set', category: 'ink', brand: 'Canon', price: 550, image: 'https://www.inksystem.biz/uploaded/img/shop/14389/product-card-750x492-ink-key-inksystem-70ml_cmyk-1-min.jpg', description: 'Якісний аналог.', inStock: true, refill: true, isBulk: true },
  { id: 'i021', name: 'ColorWay картридж аналог HP', category: 'ink', brand: 'HP', price: 300, image: 'https://p.ua/media/catalog/product/cache/e97bfe48fc3322ec3691b281a1a6a88d/a/n/analog-hp-21xl-black-chernyj-kartridzh-sovmestimyj-neoriginal-nyj-hc-e01x-microjet.webp', description: 'Картридж сумісний.', inStock: true, refill: true },
  { id: 'i022', name: 'WWM Black (для Epson)', category: 'ink', brand: 'Epson', price: 150, image: 'https://p.ua/media/catalog/product/cache/e97bfe48fc3322ec3691b281a1a6a88d/e/6/e64-b-4-chernila-kraska-black-chernyj-vodorastvorimye-vodnye-1000g.webp', description: 'Чорне чорнило.', inStock: true, refill: true, isBulk: true },
  { id: 'i023', name: 'Patron Cyan', category: 'ink', brand: 'Canon', price: 110, image: 'https://img.mta.ua/image/cache/data/foto/z333/333893/photos/BARVA-CHornilo-Patron-HP-CZ102CZ110-101515152515-90-g-cyan-H655397-01-600x600.jpg', description: 'Блакитне.', inStock: true, refill: true, isBulk: true },
  { id: 'i024', name: 'Barva набір для HP', category: 'ink', brand: 'HP', price: 420, image: 'https://cdn.27.ua/original/c5/11/1033489_3.jpeg', description: 'Набір.', inStock: true, refill: true, isBulk: true },

  // === TONER (Картриджі) ===
  {
    id: 't001',
    name: 'HP 30A CF230A Лазерний картридж Чорний',
    category: 'toner',
    brand: 'HP',
    price: 1850,
    image: 'https://images.prom.ua/3223546477_w640_h640_3223546477.jpg',
    description: 'Оригінальний лазерний картридж HP 30A для LaserJet Pro M203/MFP M227. Ресурс 1600 сторінок при 5% заповненні.',
    inStock: true,
    oem: true,
    refill: false,
  },
  {
    id: 't002',
    name: 'Canon 057H Лазерний картридж (велика ємність)',
    category: 'toner',
    brand: 'Canon',
    price: 2600,
    image: 'https://a.428.ua/img/3554682/3000/2000/kartridzh_powerplant_canon_crg-057h_pp-crg-057h~792~502.jpg',
    description: 'Оригінальний картридж підвищеної ємності для i-SENSYS MF443dw/MF445dw. Ресурс 10 000 сторінок.',
    inStock: true,
    oem: true,
    refill: false,
  },
  {
    id: 't003',
    name: 'Compatibles Epson S110079 Сумісний картридж Cyan',
    category: 'toner',
    brand: 'Compatibles',
    price: 680,
    image: 'https://cdn11.bigcommerce.com/s-m27pe4qb0c/images/stencil/300x300/products/438/4160/e78ca3f1-973f-471e-9495-e6ba5981e9a7__88099.1716102320.jpg?c=2',
    description: 'Сумісний кольоровий картридж для Epson AL-C300/C400. Ресурс 3000 сторінок. Гарантована якість друку.',
    inStock: true,
    oem: false,
    refill: true,
  },
  { id: 't004', name: 'Canon 054H Black', category: 'toner', brand: 'Canon', price: 2900, image: 'https://kvarta.ua/f/2531613/2106924059/1920x/.1292612.jpg', description: 'Оригінальний картридж Canon підвищеної ємності.', inStock: true, oem: true },
  { id: 't005', name: 'Brother TN-2420 Black', category: 'toner', brand: 'Brother', price: 2200, image: 'https://images.prom.ua/4701002404_w640_h640_sovmestimyj-kartridzh-brother.jpg', description: 'Стандартний чорний тонер-картридж.', inStock: true, oem: true },
  { id: 't006', name: 'HP 106A (W1106A)', category: 'toner', brand: 'HP', price: 1450, image: 'https://images.prom.ua/5001315780_w1280_h640_5001315780.jpg', description: 'Для лазерних принтерів HP Laser 107/135.', inStock: true, oem: true },
  { id: 't007', name: 'Xerox 106R02777 Black', category: 'toner', brand: 'Xerox', price: 1950, image: 'https://www.superink.ca/cdn/shop/files/106R02777_1500x.jpg?v=1707492776', description: 'Надійний тонер для серії Phaser.', inStock: true, oem: true },
  { id: 't008', name: 'Samsung MLT-D111S', category: 'toner', brand: 'Samsung', price: 1700, image: 'https://content1.rozetka.com.ua/goods/images/big/270799505.jpg', description: 'Якісний оригінальний тонер.', inStock: true, oem: true },
  { id: 't009', name: 'ColorWay аналог HP 85A', category: 'toner', brand: 'HP', price: 650, image: 'https://tehnomarket.ua/imagephp/width=418&image=/pictures/products/products_thumbnail_ZUmzKvXkWf.jpg', description: 'Економічний сумісний тонер-картридж.', inStock: true, refill: true },
  { id: 't010', name: 'Patron аналог Canon 725', category: 'toner', brand: 'Canon', price: 580, image: 'https://itshnik.com.ua/image/cache/catalog/Cart-Patron/Can-HP/725DGL-1-700x500.jpg', description: 'Висока якість друку за доступною ціною.', inStock: true, refill: true },
  { id: 't011', name: 'WWM аналог Brother TN-2335', category: 'toner', brand: 'Brother', price: 720, image: 'https://wwm.ua/media/catalog/product/cache/366eaab42af7c91e55d01fc221896c68/a/n/analog-brother-tn2335-kartridzh-sovmestimyj-neoriginal-nyj-basf-basf-kt-tn2335_1.webp', description: 'Сумісний картридж для дому та офісу.', inStock: true, refill: true },
  { id: 't012', name: 'Barva аналог Samsung MLT-D104S', category: 'toner', brand: 'Samsung', price: 690, image: 'https://zip-center.kiev.ua/image/catalog/product-import/3/age-catalog-img_products-full_MLT-D104S-SEE_003_Right-Angle_black2.jpg', description: 'Бюджетна альтернатива оригіналам.', inStock: true, refill: true },

  // === PAPER (Папір) ===
  {
    id: 'pa001',
    name: 'Navigator Universal A4 80г/м² 500 аркушів',
    category: 'paper',
    brand: 'Navigator',
    price: 165,
    image: 'https://omixcdn.com/img/catalog/bumaga-navigator-universal-1.jpg',
    description: 'Офісний папір преміум класу A4, 80 г/м², пачка 500 аркушів. Підходить для всіх типів принтерів і копіювальних апаратів.',
    inStock: true,
    a4: true,
  },
  {
    id: 'pa002',
    name: 'Lomond Photo Paper Глянцевий A4 230г/м² 50аркушів',
    category: 'paper',
    brand: 'Lomond',
    price: 420,
    image: 'https://myprint.ua/uploads/product/gallery_image/2021/08/14/6117a6465b489/658ef6dbb9e37.webp',
    description: 'Глянцевий фотопапір для струменевого друку. 50 аркушів A4, 230 г/м², яскраві кольори, швидке висихання.',
    inStock: true,
    a4: true,
  },
  {
    id: 'pa003',
    name: 'Xerox Premier A3 80г/м² 500 аркушів',
    category: 'paper',
    brand: 'Xerox',
    price: 320,
    image: 'https://omixcdn.com/img/catalog/bumaga-ofisnaya-xerox-performer-0.jpg',
    description: 'Офісний папір формату A3, 80 г/м², пачка 500 аркушів. Кліматично нейтральне виробництво.',
    inStock: false,
    a3: true,
  },
  { id: 'pa004', name: 'Canon Red Label A4 80г/м²', category: 'paper', brand: 'Canon', price: 175, image: 'https://shop.ludwig-office.de/media/image/81/75/55/Canon-Red-Label-Zero_plt-LO.png', description: 'Високоякісний папір для інтенсивного друку.', inStock: true, a4: true },
  { id: 'pa005', name: 'HP Copy A4 80г/м²', category: 'paper', brand: 'HP', price: 155, image: 'https://images.prom.ua/5555216797_w640_h640_bumaga-ofisnaya-hp.jpg', description: 'Базовий офісний папір для повсякденних завдань.', inStock: true, a4: true },
  { id: 'pa006', name: 'Mondi IQ Premium A4 90г/м²', category: 'paper', brand: 'Mondi', price: 195, image: 'https://p1.akcdn.net/full/1161284889.mondi-a4-90-g-iq-premium-ok-mpapir370.jpg', description: 'Преміальний папір підвищеної щільності.', inStock: true, a4: true },
  { id: 'pa007', name: 'Double A A4 80г/м²', category: 'paper', brand: 'Double A', price: 180, image: 'https://www.papirus.com.ua/img/goods/88558.jpg', description: 'Відомий своєю гладкістю папір.', inStock: true, a4: true },
  { id: 'pa008', name: 'Svetocopy A4 80г/м²', category: 'paper', brand: 'Svetocopy', price: 140, image: 'https://images.prom.md/18461176_w640_h320_svetocopy-a4-80.jpg', description: 'Бюджетний варіант для масового друку.', inStock: true, a4: true },
  { id: 'pa009', name: 'Navigator A3 80г/м²', category: 'paper', brand: 'Navigator', price: 320, image: 'https://reperstore.net/77-home_default/papier-blanc-navigator-universel-a3-80g.jpg', description: 'Папір формату A3 для креслень та таблиць.', inStock: true, a3: true },
  { id: 'pa010', name: 'Xerox Premier A4 80г/м²', category: 'paper', brand: 'Xerox', price: 170, image: 'https://omixcdn.com/img/catalog/bumaga-ofisnaya-xerox-premier-tcf-0.jpg', description: 'Оптимальний папір для лазерних принтерів.', inStock: true, a4: true },
  { id: 'pa011', name: 'Canon Photo Paper Glossy A4', category: 'paper', brand: 'Canon', price: 450, image: 'https://b.428.ua/img/32863/600/600/bumaga_canon_a4_photo_paper_plus_glossy_20l_2311b019~500~500.jpg', description: 'Глянцевий фотопапір для струменевого друку.', inStock: false, a4: true },
  { id: 'pa012', name: 'Epson Glossy Photo A6 10x15', category: 'paper', brand: 'Epson', price: 210, image: 'https://www.adminmarket.ru/upload/iblock/79e/79ecef0293a8f799811d420ca07097e6.jpg', description: 'Фотопапір для друку знімків 10х15.', inStock: true, a6: true },
  { id: 'pa013', name: 'A4 Color Paper Mix (Пастельні кольори)', category: 'paper', brand: 'Unbranded', price: 250, image: 'https://d1tgqsu7rb4p76.cloudfront.net/604904/conversions/bumaga-tsvetnaya-color-a4-pastel-80gm2-rainbow-pack-light-250listov-5-tsvet-po-50list-assort-spectra-color0-product-card.jpg', description: 'Кольоровий папір для оголошень.', inStock: true, a4: true },
  { id: 'pa014', name: 'Офісний папір А5, 80 г/м2, 1000 листів idea!', category: 'paper', brand: 'Idea!', price: 205, image: 'https://fotoink.com.ua/image/cache/catalog/data/Mondi/17746-%D0%B05-700x700.jpg', description: 'Офісний папір А5, 80 г / м2, 1000 листів-підходить для струменевого і лазерного друку. Компактний формат A5 для блокнотів. ', inStock: true, a5: true },

  // === SHREDDERS (Шредери) ===
  {
    id: 'sh001',
    name: 'Fellowes Powershred 79Ci Шредер для дому',
    category: 'shredders',
    brand: 'Fellowes',
    price: 4200,
    image: 'https://mobileplanet.ua/uploads/product/2025-2-18/fellowes-79ci-f-u4679001-336755.webp',
    description: 'Домашній шредер з перехресним різанням. Знищує до 9 аркушів за раз, картки та скріпки. Бункер 20 л.',
    inStock: true,
    crossCut: true,
    sheetCapacity: 9,
  },
  {
    id: 'sh002',
    name: 'Rexel Momentum X410 Офісний шредер',
    category: 'shredders',
    brand: 'Rexel',
    price: 7800,
    image: 'https://cdn.jgbm.co.uk/assets/images/products/691602/X410SL_750x750.jpg',
    description: 'Тихий офісний шредер з авто-живленням. До 10 аркушів, рівень безпеки P-4, автоматичне подавання папера, безперервна робота.',
    inStock: true,
    crossCut: true,
    sheetCapacity: 10,
    autoFeed: true,
  },
  { id: 'sh003', name: 'Fellowes LX211', category: 'shredders', brand: 'Fellowes', price: 11500, image: 'https://www.shreddingmachines.co.uk/zoomimages/5050201.1.jpg', description: 'Високопродуктивний шредер з інтелектуальною технологією подачі. Безшумна робота.', inStock: true, crossCut: true, hds: true },
  { id: 'sh004', name: 'Rexel Auto+ 300M', category: 'shredders', brand: 'Rexel', price: 28000, image: 'https://www.rexeleurope.com/azure/catalogfiles/products/Desktop__80631F61E33DB98F9E4883646FCAD471__500__rx_2020300M_capacity_autofeed_etail1-f329f679a52f3f7cfbde44d2ed0eb92d.png', description: 'Автоматичний шредер корпоративного класу з мікро-різанням.', inStock: true, autoFeed: true, hds: true },
  { id: 'sh005', name: 'HSM Shredstar X10', category: 'shredders', brand: 'HSM', price: 5400, image: 'https://www.officetime.com.ua/files/2017/03_06/13_44/u_files_store_13_150729.jpg', description: 'Надійний знищувач документів для малого офісу з функцією анти-затору.', inStock: false, crossCut: true },
  { id: 'sh006', name: 'Dahle PaperSafe 120', category: 'shredders', brand: 'Dahle', price: 6200, image: 'https://www.novus-dahle.com/en/wp-content/uploads/2023/12/Dahle_Dahle_Shredder_PaperSafe_120_product_03__20230605160537_374150.jpg', description: 'Компактний та потужний шредер з автоматичною подачею.', inStock: true, crossCut: true, autoFeed: true },
  { id: 'sh007', name: 'Fellowes AutoMax 100M', category: 'shredders', brand: 'Fellowes', price: 15900, image: 'https://res.cloudinary.com/rsc/image/upload/b_rgb:FFFFFF,c_pad,dpr_2.625,f_auto,h_214,q_auto,w_380/c_pad,h_214,w_380/Y2702278-03?pgw=1', description: 'Повністю автоматичний шредер, що не потребує присутності користувача.', inStock: true, autoFeed: true, hds: true },
  { id: 'sh008', name: 'Rexel Momentum X420', category: 'shredders', brand: 'Rexel', price: 9200, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgjOUfc-lpr2xWiUW7DhLJlAZIGNvWaYtl9w&s', description: 'Потужний шредер для великих обсягів паперу.', inStock: true, crossCut: true, hds: true },

  // === LAMINATORS (Ламінатори) ===
  {
    id: 'l001',
    name: 'GBC Foton 30 Ламінатор A4 автоматичний',
    category: 'laminators',
    brand: 'GBC',
    price: 5600,
    image: 'https://wows.com.my/wp-content/uploads/2024/12/gbc-foton30-laminator.jpg',
    description: 'Автоматичний ламінатор A4 для офісу. Швидкість 30 см/хв, підтримує плівки 80-125 мкм, готовий до роботи за 60 сек.',
    inStock: true,
    a4: true,
  },
  {
    id: 'l002',
    name: 'Leitz iLAM Home Office A3 Ламінатор',
    category: 'laminators',
    brand: 'Leitz',
    price: 3100,
    image: 'https://st-ok.com.ua/wp-content/uploads/2021/06/laminator-leitz-ilam-office-pro-a3-5e034e63ac57b_5e74a24ad318d.jpg',
    description: 'Ламінатор A3 для дому та офісу. Підтримує гарячу та холодну ламінацію, плівки 80-250 мкм, формат до A3.',
    inStock: true,
    coldLamination: true,
    a3: true,
  },
  { id: 'l003', name: 'Fellowes Saturn 3i A3', category: 'laminators', brand: 'Fellowes', price: 4500, image: 'https://images.prom.ua/3567810557_w640_h640_laminator-fellowes-saturn.jpg', description: 'Офісний ламінатор з функцією швидкого нагріву за 60 секунд.', inStock: true, a3: true },
  { id: 'l004', name: 'Rexel Inspire+ A4', category: 'laminators', brand: 'Rexel', price: 1800, image: 'https://m.media-amazon.com/images/I/71yeaKnm2uL._AC_UF894,1000_QL80_.jpg', description: 'Компактний ламінатор для домашнього використання.', inStock: true, a4: true },
  { id: 'l005', name: 'Fellowes Lunar A4', category: 'laminators', brand: 'Fellowes', price: 1600, image: 'https://content2.rozetka.com.ua/goods/images/big/183441820.jpg', description: 'Простий та надійний ламінатор початкового рівня.', inStock: true, a4: true },
  { id: 'l006', name: 'GBC Fusion 3000L A3', category: 'laminators', brand: 'GBC', price: 3900, image: 'https://5.imimg.com/data5/LC/DQ/MY-4191973/gbc-fusion-3000l-a3-pouch-lamination-500x500.jpg', description: 'Високопродуктивний ламінатор з автоматичним налаштуванням швидкості.', inStock: true, a3: true, coldLamination: true },
  { id: 'l007', name: 'Leitz iLAM Touch A4', category: 'laminators', brand: 'Leitz', price: 5200, image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsYM2AUfptMVGrq5HePW9yEAyhgi8dFx6WHA&s', description: 'Інтелектуальний ламінатор, що сам визначає товщину плівки.', inStock: false, a4: true, coldLamination: true },
  { id: 'l008', name: 'Agent LM-A3 250', category: 'laminators', brand: 'Agent', price: 2900, image: 'https://a-techno.com.ua/assets/images/items/1328681/0219448001691735844.webp', description: 'Надійний офісний варіант з підтримкою формату A3.', inStock: true, a3: true },
  { id: 'l010', name: 'GBC Inspire A3', category: 'laminators', brand: 'GBC', price: 2500, image: 'https://m.media-amazon.com/images/I/81+FPWoLsGL.jpg', description: 'Базова модель формату A3 для легких завдань.', inStock: true, a3: true },

  // === PROJECTORS (Проєктори) ===
  {
    id: 'pr001',
    name: 'Epson EB-W52 WXGA Проектор 4000 лм',
    category: 'projectors',
    brand: 'Epson',
    price: 32800,
    image: 'https://click.ua/content/shop/products/186533/photos/proektor-epson-ebminusw55-left-parenthesisv11hb58042right-parenthesis-800x417-b813.jpg',
    description: 'Бізнес-проектор WXGA (1280x800), 4000 лм, Wi-Fi, HDMI, USB. Ідеальний для конференц-залів і аудиторій.',
    inStock: true,
    wireless: true,
  },
  {
    id: 'pr002',
    name: 'Optoma UHD38x 4K Ігровий Проєктор',
    category: 'projectors',
    brand: 'Optoma',
    price: 41500,
    image: 'https://gamezone.com.ua/media/gamezone/gamezone/galley/image/L/L/Z/media_240222_122037.webp',
    description: '4K UHD проектор для ігор та домашнього кінотеатру. 3800 лм, 4K, 240 Гц, HDMI 2.0, HDR10, час відгуку 4.2 мс.',
    inStock: true,
    hd: true,
  },
  { id: 'pr003', name: 'BenQ W1800i 4K', category: 'projectors', brand: 'BenQ', price: 34000, image: 'https://content2.rozetka.com.ua/goods/images/big/296787485.jpg', description: 'Кінотеатральний проектор з підтримкою HDR-PRO.', inStock: true, hd: true, wideFormat: true },
  { id: 'pr004', name: 'Epson EH-LS300B', category: 'projectors', brand: 'Epson', price: 65000, image: 'https://i.eldorado.ua/500x240/goods_images/1083543/7948738-1660058182.jpg', description: 'Ультракороткофокусний лазерний проектор.', inStock: true, laser: true, wireless: true },
  { id: 'pr005', name: 'ViewSonic PX701-4K', category: 'projectors', brand: 'ViewSonic', price: 29500, image: 'https://image.ceneostatic.pl/data/article_picture/f5/01/85ce-f03a-4bcb-8457-010ba83a108a_large.jpg', description: 'Яскравий 4K проектор для ігор та кіно.', inStock: true, hd: true, wideFormat: true },
  { id: 'pr006', name: 'LG HU70LS', category: 'projectors', brand: 'LG', price: 42000, image: 'https://www.lg.com/ru/images/projectors/md06217976/gallery/medium09.jpg', description: '4K проектор з LED джерелом світла.', inStock: false, hd: true, wireless: true },
  { id: 'pr007', name: 'XGIMI Horizon Pro', category: 'projectors', brand: 'XGIMI', price: 48000, image: 'https://content1.rozetka.com.ua/goods/images/big/181819155.jpg', description: 'Інтелектуальний 4K проектор з Android TV.', inStock: true, hd: true, wireless: true },
  { id: 'pr008', name: 'Acer Predator GM712', category: 'projectors', brand: 'Acer', price: 36000, image: 'https://content2.rozetka.com.ua/goods/images/big/333766685.jpg', description: 'Ігровий проектор з високою частотою оновлення.', inStock: true, hd: true, wideFormat: true },
  { id: 'pr009', name: 'Xiaomi Mi Smart 2 Pro', category: 'projectors', brand: 'Xiaomi', price: 21000, image: 'https://i.mi.ua/media/catalog/product/cache/3/image/710x600/602f0fa2c1f0d1ba5e241f914e856ff9/import/159837946.webp', description: 'Компактний Full HD проектор з автокорекцією.', inStock: true, wireless: true, wideFormat: true },
  { id: 'pr010', name: 'Panasonic PT-VMZ51', category: 'projectors', brand: 'Panasonic', price: 72000, image: 'https://panashop.ua/image/cache/catalog/products/dlya-biznesa/proektory/portativnye-ofisnye-lcd-proektory-s-lazernym-istochnikom-sveta/pt-vmz51/proektor-panasonic-pt-vmz51-lcd-wuxga-700x700.png', description: 'Професійний лазерний проектор для великих конференц-залів.', inStock: true, laser: true, wideFormat: true },

  // === PLOTTERS (Плотери) ===
  {
    id: 'pl001',
    name: 'HP DesignJet T650 36" Плотер A0',
    category: 'plotters',
    brand: 'HP',
    price: 58000,
    image: 'https://content.rozetka.com.ua/goods/images/big/371705565.png',
    description: 'Широкоформатний струменевий плотер 36 дюймів для CAD та GIS. Wi-Fi, USB, Ethernet. Рулонний та аркушевий папір.',
    colorPrint: true,
    wireless: true,
    inkjet: true,
  },
  {
    id: 'pl002',
    name: 'Epson SureColor SC-T3100 Широкоформатний',
    category: 'plotters',
    brand: 'Epson',
    price: 62000,
    image: 'https://cdn-eu.aglty.io/epson/productimages/26854-productpicture-lores-ix-sc-t3100_main.png',
    description: 'Плотер A1 з роздільністю 2400 dpi. Печатка на рулонному папері, підставка в комплекті, Wi-Fi, USB 3.0.',
    colorPrint: true,
    wireless: true,
    inkjet: true,
  },
  {
    id: 'pl003',
    name: 'Canon imagePROGRAF TC-20',
    category: 'plotters',
    brand: 'Canon',
    price: 32000,
    image: 'https://www.lds.com.ua/assets/components/phpthumbof/cache/0b3b6b3c272ae1ff8b94ed676993cb99.db414f35d04fbc82f13e287ee3ca15c519783.png',
    description: 'Настільний плотер A1 для архітекторів та дизайнерів. Компактний, економний.',
    inStock: false,
    colorPrint: true,
    wireless: true,
    inkjet: true
  },
  {
    id: 'pl004',
    name: 'HP DesignJet T250 24"',
    category: 'plotters',
    brand: 'HP',
    price: 29500,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCpE_SHouPLeVOsvLHS2n_jK69mZ7ULyX9Zg&s',
    description: 'Найкомпактніший плотер HP 24 дюйми. Ідеальний для малого офісу.',
    inStock: true,
    wireless: true,
    inkjet: true
  },
  {
    id: 'pl005',
    name: 'Epson SureColor SC-T5100',
    category: 'plotters',
    brand: 'Epson',
    price: 62000,
    image: 'https://click.ua/content/shop/products/176401/photos/printer-epson-surecolor-sc-t5100-36-c11cf12301a0-800-632-e51d.jpg',
    description: '36-дюймовий плотер з високою деталізацією для технічних креслень.',
    inStock: true,
    colorPrint: true,
    wireless: true,
    inkjet: true
  },
  {
    id: 'pl006',
    name: 'Canon imagePROGRAF TM-300',
    category: 'plotters',
    brand: 'Canon',
    price: 68000,
    image: 'https://cdn.media.amplience.net/i/canon/IMAGE%207?w=700&qlt=70',
    description: 'Високошвидкісний плотер для друку плакатів та креслень. Дуже тихий.',
    inStock: true,
    colorPrint: true,
    inkjet: true
  },
  {
    id: 'pl007',
    name: 'Brother ScanNCut SDX1200',
    category: 'plotters',
    brand: 'Brother',
    price: 18500,
    image: 'https://dhssewing.co.za/wp-content/uploads/2021/01/SNC-DX-Web-Image_Direct-Cut_Half-Cut-600x404.png',
    description: 'Компактний ріжучий плотер для творчості та тканини. Вбудований сканер.',
    inStock: true,
    isCutting: true
  },
  {
    id: 'pl008',
    name: 'Graphtec CE7000-60',
    category: 'plotters',
    brand: 'Graphtec',
    price: 45000,
    image: 'https://www.larsen.ua/upload/iblock/690/CE7000-60E-03.jpg',
    description: 'Професійний ріжучий плотер для вінілу та наклейок. Висока точність.',
    inStock: false,
    isCutting: true
  },
  {
    id: 'pl009',
    name: 'Mimaki JFX200-2513',
    category: 'plotters',
    brand: 'Mimaki',
    price: 4200000,
    image: 'https://mimaki.com/archives/002/201507/5ac434d0987be6190f2f456bc7edc667.png',
    description: 'Потужний планшетний УФ-принтер/плотер для друку на твердих матеріалах.',
    inStock: true,
    isFlatbed: true
  },
  {
    id: 'pl010',
    name: 'Roland VersaUV LEF2-200',
    category: 'plotters',
    brand: 'Roland',
    price: 380000,
    image: 'https://www.foroffice.ru/upload/iblock/d53/Roland_VersaUV_LEF2_200_open.jpg',
    description: 'Компактний планшетний принтер для брендування сувенірної продукції.',
    inStock: true,
    isFlatbed: true
  },
];

export const CATEGORY_BRANDS: Record<string, string[]> = {
  printers: ['HP', 'Epson', 'Canon', 'Brother'],
  scanners: ['Epson', 'Canon', 'HP'],
  mfp: ['HP', 'Canon', 'Brother'],
  ink: ['HP', 'Epson', 'Canon', 'Brother', 'ColorWay', 'WWM', 'Patron', 'Barva'],
  toner: ['HP', 'Canon', 'Brother', 'Xerox', 'Samsung', 'Patron', 'WWM', 'Barva'],
  paper: ['Navigator', 'Canon', 'HP', 'Mondi', 'Double A', 'Svetocopy', 'Xerox', 'Epson', 'Idea!'],
  shredders: ['Fellowes', 'Rexel', 'HSM', 'Dahle'],
  laminators: ['Fellowes', 'Rexel', 'GBC', 'Leitz', 'Agent'],
  projectors: ['Epson', 'Optoma', 'BenQ', 'ViewSonic', 'LG', 'XGIMI', 'Acer', 'Xiaomi', 'Panasonic'],
  plotters: ['HP', 'Epson', 'Canon', 'Brother', 'Graphtec', 'Mimaki', 'Roland'],
};

export const BRANDS = [...new Set(products.map((p) => p.brand))].sort();

export const MAX_PRICE = Math.max(...products.map((p) => p.price));
export const MIN_PRICE = Math.min(...products.map((p) => p.price));

export const getPriceRangeByCategory = (categoryPrefix: string | 'all') => {
  const filteredProducts = categoryPrefix === 'all' 
    ? products 
    : products.filter((p) => p.id.startsWith(categoryPrefix));

  if (filteredProducts.length === 0) return { min: 0, max: 10000 };

  const prices = filteredProducts.map((p) => p.price);
  return {
    min: Math.min(...prices),
    max: Math.max(...prices),
  };
};

export const getPriceRange = (prefix: string | 'all') => {
  const filtered = prefix === 'all' 
    ? products 
    : products.filter(p => p.id.startsWith(prefix));
  
  if (filtered.length === 0) return { min: 0, max: 10000 };
  
  const prices = filtered.map(p => p.price);
  return { min: Math.min(...prices), max: Math.max(...prices) };
};
